"""Initial migration

Revision ID: 07443f6c30b2
Revises: 
Create Date: 2024-12-12 18:03:54.709912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07443f6c30b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('spins', sa.Integer(), nullable=True),
    sa.Column('daily_spin', sa.Float(), nullable=True),
    sa.Column('my_referral', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('tasks')
    # ### end Alembic commands ###
