"""Fix migration

Revision ID: 2f175f83a576
Revises: 7bd648ae59ad
Create Date: 2024-12-15 18:55:32.133477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f175f83a576'
down_revision = '7bd648ae59ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribe_checker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_wait', sa.Float(), server_default=sa.text('(1734278132.0725126)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribe_checker', schema=None) as batch_op:
        batch_op.drop_column('time_wait')

    # ### end Alembic commands ###
