"""Initial migration

Revision ID: 49d793d68b56
Revises: bd234b434d41
Create Date: 2024-12-15 15:56:34.476046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d793d68b56'
down_revision = 'bd234b434d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('total_spins',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('total_spins',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
