"""Initial migration

Revision ID: 5f4e95b2ff82
Revises: 691288c1afa4
Create Date: 2024-12-12 18:29:41.949178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4e95b2ff82'
down_revision = '691288c1afa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('get_bonus_for_two_friends', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('get_bonus_for_two_friends')

    # ### end Alembic commands ###
