"""Initial migration

Revision ID: 691288c1afa4
Revises: 9b876209e5ba
Create Date: 2024-12-12 18:26:48.777909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691288c1afa4'
down_revision = '9b876209e5ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_manager', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('link_partner', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('link_gift', sa.String(length=255), nullable=False))
        batch_op.drop_column('key')
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('key', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('link_gift')
        batch_op.drop_column('link_partner')
        batch_op.drop_column('link_manager')

    # ### end Alembic commands ###
