"""Fix migration

Revision ID: 7bd648ae59ad
Revises: 49d793d68b56
Create Date: 2024-12-15 17:56:07.068069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd648ae59ad'
down_revision = '49d793d68b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribe_checker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('status_sub', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('spins',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('daily_spin',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('my_referral',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('get_bonus_for_two_friends',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('total_spins',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('total_spins',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('get_bonus_for_two_friends',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('my_referral',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('daily_spin',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('spins',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('subscribe_checker')
    # ### end Alembic commands ###
