"""Обновление поля get_bonus_for_two_friends

Revision ID: 9a20c2cd7196
Revises: 2f175f83a576
Create Date: 2024-12-16 17:09:16.637779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a20c2cd7196'
down_revision = '2f175f83a576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('get_bonus_for_two_friends',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('get_bonus_for_two_friends',
               existing_type=sa.String(length=2),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
